### ISSUE TITLE
bug (parser function): fixed wrapper height causes overlays

### ISSUE THREAD

**Issue by gesinn-it-gea** [SemanticMediaWiki/KnowledgeGraph#6]
Given a wiki with Chameleon skin. When source editing a page with the `#knowledgegraph` parser function, a preview will overlay the wiki text editor making the text inaccessible.

![image](https://github.com/user-attachments/assets/b51088b4-e816-4ba1-9ee9-f1b00c988892)

The same happens on regular pages:

![image](https://github.com/user-attachments/assets/5d79f588-4783-4db2-badd-2524e3a09ffb)

**Comment by thomas-topway-it** [comment]
@gesinn-it-gea I cannot reproduce with chameleon and last version, could you please post the styles from the inspector ? -- or is there a public url that I can access ?

**Comment by gesinn-it-gea** [comment]
Currently I do not have a public URL,

- MW 1.39.7
- mediawiki/chameleon-skin 4.3.0
- KnowledgeGraph 55874d64946f34ae6acbc6864d1ed8ad293a188d
- ... and some other extension that should not cause the style height set to 28px

The problem is the style attribute height set to 28px in my case.

**Comment by gesinn-it-gea** [comment]
```
## -------- Chameleon --------
# Chameleon included via Composer
wfLoadExtension( 'Bootstrap' );
wfLoadSkin( 'chameleon' );
$wgDefaultSkin="chameleon";
$egChameleonLayoutFile= $IP . "/skins/chameleon/layouts/fixedhead.xml";
## ======== Chameleon ========
```

**Comment by gesinn-it-gea** [comment]
In Vector (just commenting Chameleon), rendering works as expected. JS console:

![image](https://github.com/user-attachments/assets/4f37c5fd-2aab-4679-99e5-44f57569cfac)

**Comment by thomas-topway-it** [comment]
@gesinn-it-gea I remember I had already fixed this issue and perhaps I've found it shows here https://test.knowledge.wiki/SemanticGraph?useskin=chameleon

**Comment by gesinn-it-gea** [comment]
@thomas-topway-it thanks for looking into it. Is the fix you have mentioned already committed here?

**Comment by thomas-topway-it** [comment]
it should, so it is strange it happens, now I'm trying to update the KG extension on the server to check if it is caused by an old version. If this is not the case, I can debug it

**Comment by gesinn-it-gea** [comment]
Your wiki show's the same bug. Try to add some text before and after the parser function call to make it easier to see the overlay.

![image](https://github.com/user-attachments/assets/7915c395-0afe-46e4-afe5-0e944014634e)

**Comment by thomas-topway-it** [comment]
I have now installed the last version and looks correct https://test.knowledge.wiki/SemanticGraph

**Comment by thomas-topway-it** [comment]
git clone https://github.com/SemanticMediaWiki/KnowledgeGraph

**Comment by thomas-topway-it** [comment]
ah, no, one second, there wasn't the skin https://test.knowledge.wiki/SemanticGraph?useskin=chameleon

**Comment by gesinn-it-gea** [comment]
Please edit your example page to have some text before and after the parser function

```
TEXT BEFORE
{{#knowledgegraph...
TEXT AFTER
```

**Comment by thomas-topway-it** [comment]
I don't have account on this wiki, however I'm trying to debug it anyway, I have identified the issue (at DOM level)

**Comment by gesinn-it-gea** [comment]
@krabina can you please edit the example page as described in my last comment

https://test.knowledge.wiki/SemanticGraph

**Comment by thomas-topway-it** [comment]
for now I've fixed this https://github.com/SemanticMediaWiki/KnowledgeGraph/commit/4a2483f7aacd7785edc7644a56bec0dfebdc6f9c    a quite bad inadvertence, my fault

**Comment by thomas-topway-it** [comment]
there is still some inconsistency between chameleon and vector, I'm trying to find out the reason

**Comment by thomas-topway-it** [comment]
I did a better assessment https://github.com/SemanticMediaWiki/KnowledgeGraph/commit/f253f947062ffa35c053ebcc207516bdb4430945

so somehow (either Chameleon or Bootstrap) transform the jquery `width()` and `height()` functions to have absolute values, so now we are using plain javascript

**Comment by gesinn-it-gea** [comment]
works perfect! Many thanks for having a look at this. One hint: there seems to be still some console output. This should imho be removed.

**Comment by thomas-topway-it** [comment]
ok, done https://github.com/SemanticMediaWiki/KnowledgeGraph/commit/7d9133396e12e7a089a171e33305bc0b6931d7df
